server:
  port: 9100
spring:
  application:
    # 这里的 unique-name 来自于虚拟机启动时的参数-Dunique-name=-zjluvcn
    name: atm-gateway-service
  # spring.profiles.active=aggregation 指定网关项目启动后继续读取 application-aggregation.yaml 配置文件
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.58.100:8848 # nacos地址
