dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/atm?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 6y7u8i9o@cn

rules:
  - !SHARDING
    tables:
      t_user:
        actualDataNodes: ds_${0}.t_user_${0..9}
        databaseStrategy:
          standard:
            shardingColumn: identity_id
            shardingAlgorithmName: user_database_hash_mod
        tableStrategy:
          standard:
            shardingColumn: identity_id
            shardingAlgorithmName: user_table_hash_mod
    shardingAlgorithms:
      user_database_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 1
      user_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 10
  - !ENCRYPT
    tables:
      t_user:
        columns:
          identity_id:
            cipherColumn: identity_id
            encryptorName: common_encryptor
          phone:
            cipherColumn: phone
            encryptorName: common_encryptor
          address:
            cipherColumn: address
            encryptorName: common_encryptor
    encryptors:
      common_encryptor:
        type: AES
        props:
          aes-key-value: d6oadClrrb9A3GWo
props:
  sql-show: true